version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: todo_app
    restart: always
    ports:
      - "7540:7540"
    environment:
      TODO_PORT: 7540
      DATABASE_URL: "postgres://postgres:postgres@db:5432/todo?sslmode=disable"
      TODO_PASSWORD: "1234"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
